# Generated by Django 5.0.1 on 2024-03-03 18:31

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(help_text='Unique reference number for the document.', max_length=255, unique=True)),
                ('document_name', models.CharField(help_text='Name of the document.', max_length=255)),
                ('document_description', models.TextField(blank=True, help_text="Optional description of the document's content.")),
                ('approval_date', models.DateField(blank=True, help_text='Date the document was approved.', null=True)),
                ('council_resolution_number', models.CharField(blank=True, help_text='Council resolution number associated with the document.', max_length=255)),
                ('approved', models.BooleanField(default=False, help_text='Indicates whether the document is approved.')),
                ('under_review', models.BooleanField(default=False, help_text='Indicates whether the document is under review.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the document was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the document was last updated.')),
                ('document_file', models.FileField(default='', help_text='Upload the document file.', upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
